-- Hosted ReconX Elite Supabase schema.
-- Run this in the Supabase SQL editor for the frontend-hosted target/notes flow.

create table if not exists public.targets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  domain text not null,
  notes text default '',
  created_at timestamptz not null default now(),
  unique (user_id, domain)
);

alter table public.targets enable row level security;

drop policy if exists "targets_select_own" on public.targets;
create policy "targets_select_own"
  on public.targets for select
  using (auth.uid() = user_id);

drop policy if exists "targets_insert_own" on public.targets;
create policy "targets_insert_own"
  on public.targets for insert
  with check (auth.uid() = user_id);

drop policy if exists "targets_update_own" on public.targets;
create policy "targets_update_own"
  on public.targets for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "targets_delete_own" on public.targets;
create policy "targets_delete_own"
  on public.targets for delete
  using (auth.uid() = user_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  message text not null,
  read boolean not null default false,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
  on public.notifications for select
  using (auth.uid() = user_id);

drop policy if exists "notifications_insert_own" on public.notifications;
create policy "notifications_insert_own"
  on public.notifications for insert
  with check (auth.uid() = user_id);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own"
  on public.notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "notifications_delete_own" on public.notifications;
create policy "notifications_delete_own"
  on public.notifications for delete
  using (auth.uid() = user_id);
