/**
 * ReportDownload.jsx - Report export component for ReconX Elite.
 *
 * Features:
 * - PDF export button
 * - JSON export button
 * - One-click HackerOne report copy
 * - Download all findings as ZIP
 */

import React, { useState } from 'react';

import { backendBaseUrl } from '../api/client';

const ReportDownload = ({ scanId, targetId, findings = [], scanData = {} }) => {
  const [loading, setLoading] = useState({
    pdf: false,
    json: false,
    hackerone: false,
    zip: false,
  });

  const [copied, setCopied] = useState(false);

  const handleExport = async (format) => {
    setLoading((prev) => ({ ...prev, [format]: true }));

    try {
      const exportData = {
        scan_id: scanId,
        target_id: targetId,
        findings,
        scan_data: scanData,
        exported_at: new Date().toISOString(),
      };

      switch (format) {
        case 'json':
          if (targetId) {
            window.open(`${backendBaseUrl}/reports/${targetId}/json`, '_blank', 'noopener,noreferrer');
          } else {
            downloadJSON(exportData, `reconx-scan-${scanId}.json`);
          }
          break;
        case 'pdf':
          if (targetId) {
            window.open(`${backendBaseUrl}/reports/${targetId}/pdf`, '_blank', 'noopener,noreferrer');
          } else {
            throw new Error('Target report is not ready yet');
          }
          break;
        default:
          break;
      }
    } catch (error) {
      console.error('Export failed:', error);
    } finally {
      setLoading((prev) => ({ ...prev, [format]: false }));
    }
  };

  const downloadJSON = (data, filename) => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateHackerOneReport = () => {
    const criticalFindings = findings.filter((f) => f.severity?.toLowerCase() === 'critical');
    const highFindings = findings.filter((f) => f.severity?.toLowerCase() === 'high');

    const targetFindings = criticalFindings.length > 0 ? criticalFindings : highFindings;

    if (targetFindings.length === 0) {
      return 'No critical or high severity findings to report.';
    }

    const finding = targetFindings[0];

    return `# ${finding.name || finding.title || 'Security Vulnerability'}

**Severity:** ${finding.severity?.toUpperCase() || 'UNKNOWN'}
**CVSS Score:** ${finding.cvss_score || 'N/A'}
**CWE:** ${finding.cwe || 'N/A'}

## Summary

${finding.description || finding.summary || 'A security vulnerability was identified during automated reconnaissance.'}

## Impact

This vulnerability could allow an attacker to ${finding.impact || 'compromise the security of the application'}.

## Steps to Reproduce

1. Visit \`${finding.host || finding.domain || 'target-domain.com'}\`
2. Navigate to \`${finding.endpoint || '/vulnerable-endpoint'}\`
3. ${finding.reproduction_steps || 'Observe the vulnerability'}

## Proof of Concept

\`\`\`
${finding.poc || 'HTTP Request/Response details would be provided here'}
\`\`\`

## Remediation

${finding.remediation || 'Implement proper input validation and sanitization.'}

## References

- ${finding.template_id ? `Nuclei Template: ${finding.template_id}` : 'Security Best Practices'}

---
Generated by ReconX Elite on ${new Date().toLocaleDateString()}
`;
  };

  const copyHackerOneReport = async () => {
    const report = generateHackerOneReport();
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const Button = ({ onClick, loading, disabled, icon, label, variant = 'default' }) => (
    <button
      onClick={onClick}
      disabled={loading || disabled}
      style={{
        ...styles.button,
        ...(variant === 'primary' ? styles.buttonPrimary : {}),
        ...(loading || disabled ? styles.buttonDisabled : {}),
      }}
    >
      {loading ? (
        <span style={styles.spinner}>⟳</span>
      ) : (
        <span style={styles.buttonIcon}>{icon}</span>
      )}
      {label}
    </button>
  );

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h3 style={styles.title}>📥 Export Reports</h3>
      </div>

      <div style={styles.content}>
        {/* Quick Actions */}
        <div style={styles.section}>
          <h4 style={styles.sectionTitle}>Quick Export</h4>
          <div style={styles.buttonGrid}>
            <Button
              onClick={() => handleExport('pdf')}
              loading={loading.pdf}
              icon="📄"
              label="Download PDF"
              variant="primary"
            />
            <Button
              onClick={() => handleExport('json')}
              loading={loading.json}
              icon="📋"
              label="Export JSON"
            />
            <Button
              onClick={() => handleExport('json')}
              loading={loading.json}
              icon="🧾"
              label="Raw Bundle"
            />
          </div>
        </div>

        {/* HackerOne Report */}
        <div style={styles.section}>
          <h4 style={styles.sectionTitle}>🐛 HackerOne Format</h4>
          <p style={styles.description}>
            Generate a HackerOne-ready report for your top severity finding. One-click copy to
            clipboard.
          </p>
          <button
            onClick={copyHackerOneReport}
            style={{
              ...styles.hackeroneButton,
              ...(copied ? styles.hackeroneCopied : {}),
            }}
          >
            <span style={styles.buttonIcon}>{copied ? '✓' : '📋'}</span>
            {copied ? 'Copied to Clipboard!' : 'Copy HackerOne Report'}
          </button>
        </div>

        {/* Report Stats */}
        <div style={styles.stats}>
          <div style={styles.statItem}>
            <span style={styles.statValue}>{findings.length}</span>
            <span style={styles.statLabel}>Findings</span>
          </div>
          <div style={styles.statItem}>
            <span style={styles.statValue}>
              {findings.filter((f) => f.severity?.toLowerCase() === 'critical').length}
            </span>
            <span style={styles.statLabel}>Critical</span>
          </div>
          <div style={styles.statItem}>
            <span style={styles.statValue}>
              {findings.filter((f) => f.severity?.toLowerCase() === 'high').length}
            </span>
            <span style={styles.statLabel}>High</span>
          </div>
        </div>

        {/* Preview hint */}
        <div style={styles.previewHint}>
          <span style={styles.hintIcon}>💡</span>
          <span style={styles.hintText}>
            PDF reports include CVSS scoring, CWE mapping, and detailed remediation steps for each
            finding.
          </span>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: {
    backgroundColor: '#1e293b',
    borderRadius: '12px',
    overflow: 'hidden',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    color: '#f1f5f9',
  },
  header: {
    padding: '16px 20px',
    borderBottom: '1px solid #334155',
  },
  title: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 600,
  },
  content: {
    padding: '20px',
  },
  section: {
    marginBottom: '24px',
  },
  sectionTitle: {
    margin: '0 0 12px 0',
    fontSize: '14px',
    fontWeight: 600,
    color: '#cbd5e1',
  },
  description: {
    fontSize: '13px',
    color: '#94a3b8',
    marginBottom: '12px',
    lineHeight: '1.5',
  },
  buttonGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: '10px',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '12px 16px',
    backgroundColor: '#334155',
    color: '#f1f5f9',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  buttonPrimary: {
    backgroundColor: '#6366f1',
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  buttonIcon: {
    fontSize: '16px',
  },
  hackeroneButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '14px 20px',
    backgroundColor: '#0f172a',
    color: '#f1f5f9',
    border: '2px solid #ec4899',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  hackeroneCopied: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  spinner: {
    display: 'inline-block',
    animation: 'spin 1s linear infinite',
  },
  stats: {
    display: 'flex',
    gap: '24px',
    padding: '16px',
    backgroundColor: '#0f172a',
    borderRadius: '8px',
    marginBottom: '16px',
  },
  statItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  statValue: {
    fontSize: '20px',
    fontWeight: 700,
    color: '#f1f5f9',
  },
  statLabel: {
    fontSize: '11px',
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  previewHint: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    padding: '12px',
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    borderLeft: '3px solid #f59e0b',
  },
  hintIcon: {
    fontSize: '14px',
    flexShrink: 0,
  },
  hintText: {
    fontSize: '12px',
    color: '#94a3b8',
    lineHeight: '1.5',
  },
};

export default ReportDownload;
